# Generated by Django 3.0.5 on 2020-04-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0002_auto_20200421_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.CharField(default='aravind', max_length=120),
            preserve_default=False,
        ),
    ]
