# Generated by Django 3.0.5 on 2020-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_auto_20200406_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image1', upload_to='images/'),
            preserve_default=False,
        ),
    ]
