# Generated by Django 3.0.5 on 2020-04-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('mob_name', models.CharField(max_length=200)),
                ('spec', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('mob_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.category')),
            ],
        ),
    ]
