# Generated by Django 3.0.5 on 2020-04-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0004_auto_20200409_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
